import type { Metadata } from "next";
import "./globals.css";
import BoidsBackground from "@/components/layout/boids-background";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App", // TODO
  description: "Generated by create next app", // TODO
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-mono antialiased`} // TODO font
      >
        {/* Google tag (gtag.js) */}
        <Script
          id="gtag-1"
          src="https://www.googletagmanager.com/gtag/js?id=G-MYPY986RMT"
          strategy="afterInteractive"
        />
        {/* Google tag (gtag.js) */}
        <Script id="gtag-2" strategy="afterInteractive">
          {`
          // Google tag (gtag.js)
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-MYPY986RMT');
        `}
        </Script>
        <div className="h-screen p-[2%] bg-neutral-200">
          <div className="relative bg-neutral-200 border border-neutral-950 text-neutral-950 rounded-xl w-full h-full">
            test
            <BoidsBackground />
            {children}
          </div>
          <p className="text-right">TODO footer</p>
        </div>
      </body>
    </html>
  );
}
