import type { Metadata } from "next";
import "./globals.css";
import BoidsBackground from "@/components/layout/boids-background";
import Script from "next/script";
import { AnmBar } from "@/components/animation/bar/anm-bar";

export const metadata: Metadata = {
  title: "Create Next App", // TODO
  description: "Generated by create next app", // TODO
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-mono antialiased`} // TODO font
      >
        {/* Google tag (gtag.js) */}
        <Script
          id="gtag-1"
          src="https://www.googletagmanager.com/gtag/js?id=G-MYPY986RMT"
          strategy="afterInteractive"
        />
        {/* Google tag (gtag.js) */}
        <Script id="gtag-2" strategy="afterInteractive">
          {`
          // Google tag (gtag.js)
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-MYPY986RMT');
        `}
        </Script>
        <div className="relative h-screen w-screen p-[2%] bg-neutral-200">
          <div className="relative h-full w-full bg-neutral-200 text-neutral-950">
            <BoidsBackground />
            {children}
          </div>
          <div className="absolute inset-0 pointer-events-none">
            <AnmBar x={2} y={2} delay={300} length={96} />
            <AnmBar x={2} y={2} delay={600} length={96} vertical />
            <AnmBar x={2} y={98} delay={900} length={96} />
            <AnmBar x={98} y={2} delay={1200} length={96} vertical />
          </div>
        </div>
      </body>
    </html>
  );
}
